spring:
  application:
    name: dashboard-collector
  data:
    mongodb:
      uri: mongodb://idashboard:${spring.data.mongodb.credents}@10.120.100.231/idashboard
      credents: ENC(4litQ6Gs+nMxT88Dxa5hy8/peZ3m46Va/aeFy2vHw/PFqoBDhVseIETBNKgPnimJ)
      collection: Repos
github:
  url: "https://api.github.com"
  token: "ee4ad27c3877b7bda506179cb547b6ad2d5478bc"
scheduler:
  cron: 0 0/1 * * * *
  enable: true
server:
  port: 9090
logging:
  level:
    com.cognizant.dashboard.collectors.github.clients.GitHubClient: OFF

  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'

jasypt:
  encryptor:
    password: dndCMiFLdGR5dktqJnY0dQ==
    bean: JasyptEncryptorBean
